[package]
name = "pamixer"
version = "1.1.1"
edition = "2021"

[dependencies]
regex = "1.7"
sarge = "2.0"

eframe = {version = "0.21", optional = true}

[features]
default = ["gui"]
gui = ["dep:eframe"]
